server:
  port: 8080

spring:
  main:
    banner-mode: "console"
  thymeleaf:
    cache: false
  swagger:
    enable: true

logging:
  config: classpath:logback-spring.xml

mybatis:
  type-aliases-package: com.rabbits.learn.entity # 注意：对应实体类的路径
  mapper-locations: classpath*:com/rabbits/learn/**/dao/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径

pagehelper:
  helperDialect: mysql #指定分页插件使用哪种方言
  reasonable: true #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  supportMethodsArguments: true #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
