rabbits:
  test:
    string: ${random.value} # 随机字符串
    number: ${random.int} # 随机int
    longNum: ${random.long} # 随机long
    num1: ${random.int(10)} # 10以内的随机数
    num2: ${random.int[10,20]} # 10-20的随机数
    num3: ${random.uuid} #32位随机数  uuid
    num4: ${com.test.number:123}
  user:
   name: 张三
